apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainlink.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chainlink.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chainlink.selectorLabels" . | nindent 4 }}
